# Generated by Django 4.2.2 on 2023-07-13 13:39

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_prdct_image1_product_prdct_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prdct_image3',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AddField(
            model_name='product',
            name='prdct_image4',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
    ]
